const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced){document.body.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));}
const menu=$('.menu-btn');menu.addEventListener('click',()=>{let open=$('nav').classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Close menu':'Open menu');menu.firstElementChild.textContent=open?'close':'menu'});
$$('nav a').forEach(a=>a.addEventListener('click',()=>{ $('nav').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.firstElementChild.textContent='menu'}));
let ticking=false;function scrollEffect(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;$('.progress').style.width=(max?100*y/max:0)+'%';if(!reduced&&innerWidth>700&&y<1100){$('.hero-main img').style.transform=`scale(1.08) translateY(${Math.min(y*.065,55)}px)`;$('.hero-small img').style.transform=`scale(1.06) translateY(${Math.min(y*-.035,0)}px)`;}ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(scrollEffect);ticking=true}},{passive:true});scrollEffect();
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){$$('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}}),{rootMargin:'-25% 0px -60% 0px'});$$('main section[id]').forEach(s=>sectionObserver.observe(s));
$$('.gallery-filters button').forEach(b=>b.addEventListener('click',()=>{$$('.gallery-filters button').forEach(x=>x.classList.toggle('active',x===b));$$('.gallery-item').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.category!==b.dataset.filter)}));
const modal=$('#modal'),content=$('#modal-content');let modalTrigger;function openModal(html,trigger){modalTrigger=trigger||document.activeElement;content.innerHTML=html;modal.showModal()}function closeModal(){modal.close();modalTrigger?.focus()}$('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});modal.addEventListener('close',()=>modalTrigger?.focus());
function escapeHtml(s){const el=document.createElement('span');el.textContent=s;return el.innerHTML}
$$('.gallery-item').forEach(b=>b.addEventListener('click',()=>openModal(`<img class="modal-photo" src="${b.querySelector('img').src}" alt="${escapeHtml(b.querySelector('img').alt)}"><p class="modal-sub" style="margin-top:18px">${escapeHtml(b.dataset.caption)}</p>`,b)));
$('#curriculum-btn').addEventListener('click',()=>openModal(`<p class="eyebrow">ÀṢÀ ACADEMY · PROPOSED CURRICULUM</p><h3 class="modal-title">A craft worth carrying.</h3><p class="modal-sub">An illustrative learning pathway. Programme dates, instructors, fees and certification arrangements need company confirmation.</p>${[['01 · Cultural foundations','Alaga roles, family etiquette, greetings and the customary stages of a Yoruba traditional wedding.'],['02 · Voice & presence','Microphone technique, speaking clearly, songs, storytelling and respectful humour.'],['03 · Ceremony practice','Planning a running order, presenting letters, coordinating family participation and responding to changes.'],['04 · Professional practice','Client consultations, preparation, rehearsal and developing a personal hosting style.']].map(([t,p])=>`<div class="module"><h4>${t}</h4><p>${p}</p></div>`).join('')}<button class="button dark" id="academy-enquiry">Register your interest <span class="material-symbols-outlined">north_east</span></button>`));
content.addEventListener('click',e=>{if(e.target.closest('#academy-enquiry')){closeModal();$('#interest').value='Academy training';$('#contact').scrollIntoView({behavior:reduced?'auto':'smooth'});}if(e.target.closest('#bag-enquiry')){closeModal();$('#interest').value='Shop enquiry';$('textarea').value='I would like to enquire about: '+bag.join(', ')+'.';$('#contact').scrollIntoView({behavior:reduced?'auto':'smooth'});}const remove=e.target.closest('[data-remove]');if(remove){bag.splice(Number(remove.dataset.remove),1);saveBag();renderBag();}});
let bag=[];try{bag=JSON.parse(localStorage.getItem('asa-enquiry-bag')||'[]');if(!Array.isArray(bag))bag=[];bag=bag.filter(x=>typeof x==='string')}catch{}function saveBag(){try{localStorage.setItem('asa-enquiry-bag',JSON.stringify(bag))}catch{}$('#bag-count').textContent=bag.length}saveBag();let toastTimer;function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
$$('[data-product]').forEach(b=>b.addEventListener('click',()=>{if(!bag.includes(b.dataset.product)){bag.push(b.dataset.product);saveBag();toast('Added to your enquiry bag')}else toast('This item is already in your enquiry bag')}));function renderBag(){content.innerHTML=`<p class="eyebrow">THE CELEBRATION EDIT</p><h3 class="modal-title">Your enquiry bag.</h3><p class="modal-sub">Concept items. Request confirmed pricing and availability through an enquiry. No payment is taken.</p>${bag.length?bag.map((x,i)=>`<div class="bag-row"><span>${escapeHtml(x)}</span><button data-remove="${i}">Remove</button></div>`).join('')+'<button class="button dark" id="bag-enquiry">Enquire about these items <span class="material-symbols-outlined">north_east</span></button>':'<p>Your bag is empty. Explore the celebration edit below.</p>'}`;}$('#bag-btn').addEventListener('click',()=>{openModal('');renderBag()});
$$('[data-interest]').forEach(a=>a.addEventListener('click',()=>$('#interest').value=a.dataset.interest));
$('#contact-form').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{localStorage.setItem('asa-last-enquiry',JSON.stringify({...data,savedAt:new Date().toISOString()}));$('.form-status').textContent='Your enquiry has been saved on this browser. It has not been sent. You can download a copy below.';let old=$('#download-enquiry');old?.remove();let btn=document.createElement('button');btn.type='button';btn.id='download-enquiry';btn.className='text-link';btn.style.color='var(--cream)';btn.textContent='Download my enquiry';btn.onclick=()=>{let blob=new Blob([Object.entries(data).map(([k,v])=>`${k}: ${v}`).join('\n')],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='asa-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('.form-status').after(btn);}catch{$('.form-status').textContent='Your browser could not save the enquiry. Please keep a copy of your message.'}});
$('#privacy-btn').addEventListener('click',()=>openModal('<h3 class="modal-title">A note on this concept.</h3><p class="modal-sub">Àṣà is a provisional brand for this website design. Service descriptions, academy modules and shop products are illustrative and need company approval. Photography is reference imagery and does not represent the company’s portfolio.</p><div class="module"><h4>Your data</h4><p>Enquiry details and your enquiry bag stay in this browser’s local storage. They are not sent to a company server. Third-party Google Fonts and reference images load from their respective providers.</p></div><button class="button dark" id="clear-data">Clear saved browser data</button>'));
content.addEventListener('click',e=>{if(e.target.closest('#clear-data')){try{localStorage.removeItem('asa-last-enquiry');localStorage.removeItem('asa-enquiry-bag')}catch{}bag=[];saveBag();closeModal();toast('Saved enquiry and bag cleared')}});$('#year').textContent=new Date().getFullYear();
